/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        border:     'var(--hairline-strong)',
        input:      'var(--surface-2)',
        ring:       'var(--ring)',
        background: 'rgb(var(--background-rgb) / <alpha-value>)',
        surface:    'rgb(var(--surface-rgb) / <alpha-value>)',
        'surface-2':'rgb(var(--surface-2-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--foreground-rgb) / <alpha-value>)',
        'foreground-muted': 'rgb(var(--foreground-muted-rgb) / <alpha-value>)',
        'foreground-faint': 'rgb(var(--foreground-faint-rgb) / <alpha-value>)',
        primary: {
          DEFAULT:    'rgb(var(--primary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--primary-fg-rgb) / <alpha-value>)',
        },
        secondary: {
          DEFAULT:    'rgb(var(--secondary-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-fg-rgb) / <alpha-value>)',
        },
        destructive: {
          DEFAULT:    'rgb(var(--destructive-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--destructive-soft-rgb) / <alpha-value>)',
        },
        muted: {
          DEFAULT:    'rgb(var(--muted-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--muted-fg-rgb) / <alpha-value>)',
        },
        accent: {
          DEFAULT:    'rgb(var(--accent-rgb) / <alpha-value>)',
          foreground: 'rgb(var(--accent-fg-rgb) / <alpha-value>)',
        },
        brand:           'rgb(var(--brand-rgb) / <alpha-value>)',
        'brand-soft':    'rgb(var(--brand-soft-rgb) / <alpha-value>)',
        success:         'rgb(var(--success-rgb) / <alpha-value>)',
        'success-soft':  'rgb(var(--success-soft-rgb) / <alpha-value>)',
        warning:         'rgb(var(--warning-rgb) / <alpha-value>)',
        'warning-soft':  'rgb(var(--warning-soft-rgb) / <alpha-value>)',
        danger:          'rgb(var(--destructive-rgb) / <alpha-value>)',
        'danger-soft':   'rgb(var(--destructive-soft-rgb) / <alpha-value>)',
        page: {
          bg:      "var(--color-page-bg)",
          surface: "var(--color-page-surface)",
          card:    "var(--color-page-card)",
        },
        shoal: {
          bg:              "rgb(var(--background-rgb) / <alpha-value>)",
          surface:         "rgb(var(--surface-rgb) / <alpha-value>)",
          "surface-2":     "rgb(var(--surface-2-rgb) / <alpha-value>)",
          fg:              "rgb(var(--foreground-rgb) / <alpha-value>)",
          "fg-muted":      "rgb(var(--foreground-muted-rgb) / <alpha-value>)",
          "fg-faint":      "rgb(var(--foreground-faint-rgb) / <alpha-value>)",
          hairline:        "var(--hairline)",
          "hairline-strong": "var(--hairline-strong)",
          primary:         "rgb(var(--primary-rgb) / <alpha-value>)",
          "primary-fg":    "rgb(var(--primary-fg-rgb) / <alpha-value>)",
          secondary:       "rgb(var(--secondary-rgb) / <alpha-value>)",
          "secondary-fg":  "rgb(var(--secondary-fg-rgb) / <alpha-value>)",
          accent:          "rgb(var(--accent-rgb) / <alpha-value>)",
          "accent-fg":     "rgb(var(--accent-fg-rgb) / <alpha-value>)",
          muted:           "rgb(var(--muted-rgb) / <alpha-value>)",
          "muted-fg":      "rgb(var(--muted-fg-rgb) / <alpha-value>)",
          brand:           "rgb(var(--brand-rgb) / <alpha-value>)",
          "brand-fg":      "rgb(var(--brand-fg-rgb) / <alpha-value>)",
          "brand-soft":    "rgb(var(--brand-soft-rgb) / <alpha-value>)",
          "brand-soft-fg": "rgb(var(--brand-soft-fg-rgb) / <alpha-value>)",
          success:         "rgb(var(--success-rgb) / <alpha-value>)",
          "success-soft":  "rgb(var(--success-soft-rgb) / <alpha-value>)",
          warning:         "rgb(var(--warning-rgb) / <alpha-value>)",
          "warning-soft":  "rgb(var(--warning-soft-rgb) / <alpha-value>)",
          danger:          "rgb(var(--destructive-rgb) / <alpha-value>)",
          "danger-soft":   "rgb(var(--destructive-soft-rgb) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      borderRadius: {
        xs:        "var(--radius-xs)",
        sm:        "var(--radius-sm)",
        DEFAULT:   "var(--radius)",
        md:        "var(--radius-md)",
        lg:        "var(--radius-lg)",
        xl:        "var(--radius-xl)",
        full:      "var(--radius-full)",
        "shoal-xs": "var(--radius-xs)",
        "shoal-sm": "var(--radius-sm)",
        "shoal":    "var(--radius)",
        "shoal-md": "var(--radius-md)",
        "shoal-lg": "var(--radius-lg)",
        "shoal-xl": "var(--radius-xl)",
      },
      boxShadow: {
        xs:          "var(--shadow-xs)",
        sm:          "var(--shadow-sm)",
        md:          "var(--shadow-md)",
        lg:          "var(--shadow-lg)",
        focus:       "var(--shadow-focus)",
        "shoal-xs":  "var(--shadow-xs)",
        "shoal-sm":  "var(--shadow-sm)",
        "shoal-md":  "var(--shadow-md)",
        "shoal-lg":  "var(--shadow-lg)",
        "shoal-focus": "var(--shadow-focus)",
      },
    },
  },
}
